spring:
  application:
    name: spotify-discovery-backend
  
  datasource:
    url: jdbc:sqlite:./data/spotify_discovery.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
    hikari:
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            scope: user-read-private,user-read-email,playlist-read-private,playlist-modify-public,playlist-modify-private,user-top-read,user-read-recently-played
            authorization-grant-type: authorization_code
            redirect-uri: ${SPOTIFY_REDIRECT_URI:http://localhost:8080/login/oauth2/code/spotify}
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

  web:
    cors:
      allowed-origins: ${FRONTEND_URL:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.spotifydiscovery: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spotify-discovery.log

# Custom application properties
spotify:
  api:
    base-url: https://api.spotify.com/v1
    accounts-url: https://accounts.spotify.com
  
# ML/Recommendation settings
recommendation:
  max-tracks-per-request: 50
  similarity-threshold: 0.7
  cache-duration-minutes: 30
